
language: python
python:
    - "3.6"

install:
    - pip install flake8 pylint Pillow

script:
    - flake8 pidi-display-pil/setup.py pidi-display-pil/pidi_display_pil --ignore E501
    - pylint pidi-display-pil/setup.py pidi-display-pil/pidi_display_pil
    - flake8 pidi-display-tk/setup.py pidi-display-tk/pidi_display_tk --ignore E501
    - pylint pidi-display-tk/setup.py pidi-display-tk/pidi_display_tk
    - flake8 pidi-display-st7789/setup.py pidi-display-st7789/pidi_display_st7789 --ignore E501
    - pylint pidi-display-st7789/setup.py pidi-display-st7789/pidi_display_st7789
